### ISSUE TITLE
chef/knife/openstack_helpers (LoadError)

### ISSUE THREAD

**Issue by josephreynolds** [chef/knife-openstack#185]
Greetings,

After an upgrade to ChefDK  0.9 , knife errors out after running any command.

```
knife node list

/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- chef/knife/openstack_helpers (LoadError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/jreynolds/.chefdk/gem/ruby/2.1.0/gems/knife-openstack-1.3.2/lib/chef/knife/openstack_flavor_list.rb:5:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:104:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:118:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:137:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:198:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:54:in `load'
	from /opt/chefdk/bin/knife:54:in `<main>'
```
chef --version
> Chef Development Kit Version: 0.9.0
> chef-client version: 12.5.1
> berks version: 4.0.1
> kitchen version: 1.4.2

partial chef gem list 
> knife-cloud (1.2.0, 1.0.1)
> knife-openstack (1.3.2)

This does not happen with knife-openstack 1.2.0

Thanks!

**Comment by jjasghar** [comment]
Wow, yeah that's a problem. I'll try to repo this asap, and update here with any findings. Thanks for the report.

**Comment by jjasghar** [comment]
Ah, that's your problem. `knife-openstack` is on [2.2.1](https://github.com/test-kitchen/kitchen-openstack/releases/tag/v2.1.1) please update. There are some major breaking changes and new options, so please take note of the README.  I'll close this, but please reopen if you repo this with the newest version.

**Comment by jjasghar** [comment]
Opps, i had both `kitchen-openstack` sand `knife-openstack` at the same time. Please disregard that previous message.

**Comment by jjasghar** [comment]
Hmm, i wasn't able to repo this. Maybe a remove off `knife-openstack` and reinstall? Those [helpers](https://github.com/chef/knife-openstack/commits/master/lib/chef/knife/openstack_helpers.rb) have been around for a long time. 

```
10:16:33 ~ > chef exec knife node list
compute1
compute2
controller
ubuntu
10:16:51 ~ > chef exec knife openstack server list
Name  Instance ID  Addresses  Flavor  Image  Keypair  State  Availability Zone
10:17:06 ~ > chef exec gem list | grep knife-openstack
knife-openstack (1.3.2)
10:17:32 ~ >
```

Please reopen this if you would like to continue still debugging this.

**Comment by alainchiasson** [comment]
Can I re-open this ? After installing knife-openstack - the above error has been encoutered running knife.

```
○ → knife
ERROR: You need to pass a sub-command (e.g., knife SUB-COMMAND)

Usage: knife sub-command (options)
    -s, --server-url URL             Chef Server URL
        --chef-zero-host HOST        Host to start chef-zero on
        --chef-zero-port PORT        Port (or port range) to start chef-zero on.  Port ranges like 1000,1010 or 8889-9999 will try all given ports until one works.
    -k, --key KEY                    API Client Key
        --[no-]color                 Use colored output, defaults to enabled
    -c, --config CONFIG              The configuration file to use
        --defaults                   Accept default values for all questions
    -d, --disable-editing            Do not open EDITOR, just accept the data as is
    -e, --editor EDITOR              Set the editor to use for interactive commands
    -E, --environment ENVIRONMENT    Set the Chef environment (except for in searches, where this will be flagrantly ignored)
        --[no-]fips                  Enable fips mode
    -F, --format FORMAT              Which format to use for output
        --[no-]listen                Whether a local mode (-z) server binds to a port
    -z, --local-mode                 Point knife commands at local repository instead of server
    -u, --user USER                  API Client Username
        --print-after                Show the data after a destructive operation
    -V, --verbose                    More verbose output. Use twice for max verbosity
    -v, --version                    Show chef version
    -y, --yes                        Say yes to all prompts for confirmation
    -h, --help                       Show this message

Available subcommands: (for details, knife SUB-COMMAND --help)

/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- chef/knife/openstack_helpers (LoadError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/achiass1/.chefdk/gem/ruby/2.1.0/gems/knife-openstack-1.3.2/lib/chef/knife/openstack_flavor_list.rb:5:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:94:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/core/subcommand_loader.rb:108:in `list_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:267:in `list_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:204:in `print_help_and_exit'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:168:in `validate_and_parse_options'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:146:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:50:in `load'
	from /opt/chefdk/bin/knife:50:in `<main>'`
```

When I remove knife-openstack using `chef gem uninstall knife-openstack` everything works again.

Here is my GEM environement

```
○ → chef gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.1.6 (2015-04-13 patchlevel 336) [x86_64-darwin12.0]
  - INSTALLATION DIRECTORY: /opt/chefdk/embedded/lib/ruby/gems/2.1.0
  - USER INSTALLATION DIRECTORY: /Users/x/.chefdk/gem/ruby/2.1.0
  - RUBY EXECUTABLE: /opt/chefdk/embedded/bin/ruby
  - EXECUTABLE DIRECTORY: /opt/chefdk/embedded/bin
  - SPEC CACHE DIRECTORY: /Users/x/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/chefdk/embedded/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-12
  - GEM PATHS:
     - /opt/chefdk/embedded/lib/ruby/gems/2.1.0
     - /Users/x/.chefdk/gem/ruby/2.1.0
```


The file is in the User install directory : 

```
○ → find /Users/x/.chefdk/gem/ruby/2.1.0 -name openstack_helpers.rb
/Users/x/.chefdk/gem/ruby/2.1.0/gems/knife-openstack-1.3.2/lib/chef/knife/openstack_helpers.rb
```

Anything else needed ? I'm also continuing to investigate.

**Comment by alainchiasson** [comment]
I saw that the reinstall removed all the gems unde /opt/chefdk (normal - since I rm -rf'ed it). But I still had quite a few gems (108) under /HOME/user/.chefdk ... 

By removing that directory and install ing the knife-openstack first everything works fine now. Will continue looking.
